canal.id = 1
canal.ip =
canal.port = 11111
canal.metrics.pull.port = 11112
canal.zkServers =
canal.withoutNetty = false
canal.serverMode = tcp
canal.destinations = example
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.user =
canal.passwd =

canal.instance.tsdb.enable = false
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml
canal.instance.global.mode = spring
canal.instance.global.lazy = false
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
