canal.instance.mysql.slaveId = 1234
canal.instance.master.address = mysql:3306
canal.instance.master.journal.name =
canal.instance.master.position =
canal.instance.master.timestamp =
canal.instance.master.gtid =

canal.instance.dbUsername = canal
canal.instance.dbPassword = Canal@123456
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName = zhiguang

canal.instance.enableDruid = false
canal.instance.filter.regex = zhiguang\\.outbox
canal.instance.filter.black.regex = mysql\\.slave_.*
